# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: CREATIVE PIONEERS
email: send@creative-pioneers.org
keywords: "CREATIVE PIONEERS, IT solutions, web development, app development, video production, graphic design, digital agency, creativity driven, innovation, stunning cinematography"
subject: Creative pioneers is an EU based group of software engineers and digital media artists producing their own content under one brand.
description: >- # this means to ignore newlines until "baseurl:"
  Creative pioneers is an EU based group of software engineers and digital media artists producing their own content under one brand.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://creative-pioneers.org" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  creative-pioneers
youtube_username: "@creative-pioneers"
http_csp: "default-src 'self'; font-src 'self' data: fonts.gstatic.com; script-src 'self' 'unsafe-inline' www.googletagmanager.com; style-src 'self' 'unsafe-inline' fonts.googleapis.com; img-src https://*; connect-src 'self' *.google-analytics.com; child-src 'none';"

permalink: /:categories/:title/

sass:
    sass_dir: _sass
    style: compressed

collections:
  services-list:
    output: true

paginate: 12
paginate_path: "/articles/page:num/"

languages: ["en", "cz"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public", "assets"]
parallel_localization: true
# Build settings
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-polyglot
  - jekyll-paginate
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
