# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: CREATIVE PIONEERS
email: no-response@creative-pioneers.org
description: >- # this means to ignore newlines until "baseurl:"
  We are Creative Pioneers, a group of digital media creators who love to share our passion for audiovisual content, IT and technology, games and open source software. We are part of WANTED.solutions company, a leading provider of innovative solutions for the digital world.
 
  We produce high-end content that covers various topics, such as how to create stunning videos and animations, how to master the latest technologies and tools, how to mod your favorite games and make them more fun and immersive, and how to contribute to the open source community and learn from other developers.
 
  We invite you to join our network and follow our updates. You will find useful tips and tricks, inspiring examples, fun challenges and exciting opportunities to collaborate with us and other creative pioneers. Whether you are a beginner or a pro, you will find something that suits your interests and skills. Let's explore the digital world together and unleash our creativity!  
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://creative-pioneers.org" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  creative-pioneers
youtube_username: creativepioneers

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
